name = "Fabric Vanilla Plus 1 . 16 . 4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b274fe654bdb9090b71b68e1cdfdd2faa6c2efe3d5f8900e3366348cfb1b9e31"

[versions]
fabric = "0.10.8"
minecraft = "1.16.4"
